apiVersion: v1
kind: PersistentVolume
metadata:
  name: srs-persistant-vol
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
